### ISSUE TITLE
Details regarding Tara stereo camera

### ISSUE THREAD

**Issue by pras2020** [Changliu52/ORB_SLAM2_ROS#1]
I saw tara launch file in your code and also your post in tara  github page has  issue
https://github.com/dilipkumar25/see3cam/issues/13

1.my first doubt is why to do calibration when they mentioned in there blog of not to do any calibration,since it is factory calibrated 
https://www.e-consystems.com/Articles/Camera/ros-support-for-tara.asp

1.How successful you were in integrating tara with orb slam2 and  how was the point cloud

**Comment by Changliu52** [comment]
Thanks for the message.
Orbslam2 needs the calibration file specified in the configuration folder, and has to be in OpenCV format, which Tara doesn’t provide.

It works relatively well in close up scene, and output a sparse point cloud. Checkout my video here: https://youtu.be/wk6kICrKlhE

Chang

**Comment by pras2020** [comment]
Can you please suggest me version of ubuntu,ROS and opencv used.I am using ubuntu 16.04,ros kinetic and opencv 3.1.0.but I couldnt build orb slam in my PC.
