### ISSUE TITLE
orb_slam2 for ROS

### ISSUE THREAD

**Issue by pras2020** [Changliu52/ORB_SLAM2_ROS#2]
Dear Changliu 

As per your documents i build ORB for ROS but i couldn't  view the orb frame and also the graph view. I have attached the screen shot below regarding the output.

![screenshot from 2018-01-11 20-52-46](https://user-images.githubusercontent.com/4815599/34832808-e3ed682c-f713-11e7-8fbc-03749a423925.png)

![screenshot from 2018-01-11 20-54-38](https://user-images.githubusercontent.com/4815599/34833160-c8c0b2a6-f714-11e7-99fc-cca6e61a8b3f.png)

**Comment by pras2020** [comment]
Its working fine after using config file in rviz.Thank you.

**Comment by Changliu52** [comment]
Awesome.

Chang
